#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 14

enum {
  sym_identifier = 1,
  anon_sym_SLASH_SLASH = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_SLASH_STAR = 4,
  aux_sym_comment_token2 = 5,
  anon_sym_SLASH = 6,
  sym_function_name = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  aux_sym_number_token1 = 10,
  aux_sym_number_token2 = 11,
  aux_sym_number_token3 = 12,
  aux_sym_number_token4 = 13,
  anon_sym_SQUOTE = 14,
  sym_char = 15,
  sym_char_escape = 16,
  anon_sym_AT = 17,
  anon_sym_PERCENT = 18,
  anon_sym_COLON = 19,
  anon_sym_DOT = 20,
  anon_sym_DASH_GT = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_entrypoint = 24,
  anon_sym_func = 25,
  anon_sym_PLUS = 26,
  anon_sym_inline = 27,
  anon_sym_height = 28,
  anon_sym_label = 29,
  anon_sym_const = 30,
  anon_sym_heap = 31,
  anon_sym_call = 32,
  anon_sym_get = 33,
  anon_sym_set = 34,
  anon_sym_out = 35,
  anon_sym_in = 36,
  anon_sym_jump = 37,
  anon_sym_branch = 38,
  sym_source_file = 39,
  sym_comment = 40,
  sym_array = 41,
  sym__literal = 42,
  sym_number = 43,
  sym_char_literal = 44,
  sym_macro = 45,
  sym_port = 46,
  sym_inst_label = 47,
  sym_data_label = 48,
  sym_definition = 49,
  sym_stack_behaviour = 50,
  sym_instruction_list = 51,
  sym_entrypoint = 52,
  sym_func = 53,
  sym_inline = 54,
  sym__instruction = 55,
  sym_height = 56,
  sym_label = 57,
  sym_const = 58,
  sym_heap = 59,
  sym_call = 60,
  sym_get = 61,
  sym_set = 62,
  sym_out = 63,
  sym_in = 64,
  sym_jump = 65,
  sym_branch = 66,
  sym_instruction = 67,
  aux_sym_source_file_repeat1 = 68,
  aux_sym_source_file_repeat2 = 69,
  aux_sym_array_repeat1 = 70,
  aux_sym_instruction_list_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [sym_function_name] = "function_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [anon_sym_SQUOTE] = "'",
  [sym_char] = "char",
  [sym_char_escape] = "char_escape",
  [anon_sym_AT] = "@",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_entrypoint] = "entrypoint",
  [anon_sym_func] = "func",
  [anon_sym_PLUS] = "+",
  [anon_sym_inline] = "inline",
  [anon_sym_height] = "height",
  [anon_sym_label] = "label",
  [anon_sym_const] = "const",
  [anon_sym_heap] = "heap",
  [anon_sym_call] = "call",
  [anon_sym_get] = "get",
  [anon_sym_set] = "set",
  [anon_sym_out] = "out",
  [anon_sym_in] = "in",
  [anon_sym_jump] = "jump",
  [anon_sym_branch] = "branch",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_array] = "array",
  [sym__literal] = "_literal",
  [sym_number] = "number",
  [sym_char_literal] = "char_literal",
  [sym_macro] = "macro",
  [sym_port] = "port",
  [sym_inst_label] = "inst_label",
  [sym_data_label] = "data_label",
  [sym_definition] = "definition",
  [sym_stack_behaviour] = "stack_behaviour",
  [sym_instruction_list] = "instruction_list",
  [sym_entrypoint] = "entrypoint",
  [sym_func] = "func",
  [sym_inline] = "inline",
  [sym__instruction] = "_instruction",
  [sym_height] = "height",
  [sym_label] = "label",
  [sym_const] = "const",
  [sym_heap] = "heap",
  [sym_call] = "call",
  [sym_get] = "get",
  [sym_set] = "set",
  [sym_out] = "out",
  [sym_in] = "in",
  [sym_jump] = "jump",
  [sym_branch] = "branch",
  [sym_instruction] = "instruction",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_instruction_list_repeat1] = "instruction_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_function_name] = sym_function_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_char] = sym_char,
  [sym_char_escape] = sym_char_escape,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_entrypoint] = anon_sym_entrypoint,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_inline] = anon_sym_inline,
  [anon_sym_height] = anon_sym_height,
  [anon_sym_label] = anon_sym_label,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_heap] = anon_sym_heap,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_branch] = anon_sym_branch,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_array] = sym_array,
  [sym__literal] = sym__literal,
  [sym_number] = sym_number,
  [sym_char_literal] = sym_char_literal,
  [sym_macro] = sym_macro,
  [sym_port] = sym_port,
  [sym_inst_label] = sym_inst_label,
  [sym_data_label] = sym_data_label,
  [sym_definition] = sym_definition,
  [sym_stack_behaviour] = sym_stack_behaviour,
  [sym_instruction_list] = sym_instruction_list,
  [sym_entrypoint] = sym_entrypoint,
  [sym_func] = sym_func,
  [sym_inline] = sym_inline,
  [sym__instruction] = sym__instruction,
  [sym_height] = sym_height,
  [sym_label] = sym_label,
  [sym_const] = sym_const,
  [sym_heap] = sym_heap,
  [sym_call] = sym_call,
  [sym_get] = sym_get,
  [sym_set] = sym_set,
  [sym_out] = sym_out,
  [sym_in] = sym_in,
  [sym_jump] = sym_jump,
  [sym_branch] = sym_branch,
  [sym_instruction] = sym_instruction,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_instruction_list_repeat1] = aux_sym_instruction_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_char_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entrypoint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_height] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_label] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_heap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_port] = {
    .visible = true,
    .named = true,
  },
  [sym_inst_label] = {
    .visible = true,
    .named = true,
  },
  [sym_data_label] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_behaviour] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction_list] = {
    .visible = true,
    .named = true,
  },
  [sym_entrypoint] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_height] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_heap] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_get] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_out] = {
    .visible = true,
    .named = true,
  },
  [sym_in] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_instruction_list = 1,
  field_instructions = 2,
  field_label = 3,
  field_locals = 4,
  field_name = 5,
  field_opcode = 6,
  field_operand = 7,
  field_params = 8,
  field_returns = 9,
  field_stack = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_instruction_list] = "instruction_list",
  [field_instructions] = "instructions",
  [field_label] = "label",
  [field_locals] = "locals",
  [field_name] = "name",
  [field_opcode] = "opcode",
  [field_operand] = "operand",
  [field_params] = "params",
  [field_returns] = "returns",
  [field_stack] = "stack",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 1},
  [10] = {.index = 12, .length = 2},
  [11] = {.index = 14, .length = 3},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_instruction_list, 1},
  [2] =
    {field_label, 0},
    {field_value, 1},
  [4] =
    {field_opcode, 0},
  [5] =
    {field_instruction_list, 2},
    {field_locals, 1},
  [7] =
    {field_operand, 1},
  [8] =
    {field_label, 0},
    {field_opcode, 1},
  [10] =
    {field_instructions, 1},
  [11] =
    {field_value, 1},
  [12] =
    {field_label, 0},
    {field_operand, 2},
  [14] =
    {field_instruction_list, 3},
    {field_name, 1},
    {field_stack, 2},
  [17] =
    {field_params, 1},
    {field_returns, 3},
  [19] =
    {field_instruction_list, 5},
    {field_locals, 4},
    {field_name, 1},
    {field_stack, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '$') ADVANCE(10);
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '+') ADVANCE(44);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '0') ADVANCE(29);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(36);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_function_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_char_escape);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'g') ADVANCE(5);
      if (lookahead == 'h') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'j') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 21:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 31:
      if (lookahead == 'g') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'y') ADVANCE(49);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_heap);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'h') ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_label);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_height);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_inline);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_entrypoint);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 16},
  [109] = {(TSStateId)(-1)},
  [110] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_function_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_char_escape] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_entrypoint] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_inline] = ACTIONS(1),
    [anon_sym_height] = ACTIONS(1),
    [anon_sym_label] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_heap] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(103),
    [sym_comment] = STATE(1),
    [sym_data_label] = STATE(41),
    [sym_definition] = STATE(78),
    [sym_entrypoint] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(49),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_entrypoint] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_height,
    ACTIONS(19), 1,
      anon_sym_label,
    ACTIONS(21), 1,
      anon_sym_const,
    ACTIONS(23), 1,
      anon_sym_heap,
    ACTIONS(25), 1,
      anon_sym_call,
    ACTIONS(27), 1,
      anon_sym_get,
    ACTIONS(29), 1,
      anon_sym_set,
    ACTIONS(31), 1,
      anon_sym_out,
    ACTIONS(33), 1,
      anon_sym_in,
    ACTIONS(35), 1,
      anon_sym_jump,
    ACTIONS(37), 1,
      anon_sym_branch,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      aux_sym_instruction_list_repeat1,
    STATE(12), 1,
      sym__instruction,
    STATE(40), 1,
      sym_inst_label,
    STATE(35), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [75] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      anon_sym_height,
    ACTIONS(50), 1,
      anon_sym_label,
    ACTIONS(53), 1,
      anon_sym_const,
    ACTIONS(56), 1,
      anon_sym_heap,
    ACTIONS(59), 1,
      anon_sym_call,
    ACTIONS(62), 1,
      anon_sym_get,
    ACTIONS(65), 1,
      anon_sym_set,
    ACTIONS(68), 1,
      anon_sym_out,
    ACTIONS(71), 1,
      anon_sym_in,
    ACTIONS(74), 1,
      anon_sym_jump,
    ACTIONS(77), 1,
      anon_sym_branch,
    STATE(12), 1,
      sym__instruction,
    STATE(40), 1,
      sym_inst_label,
    STATE(3), 2,
      sym_comment,
      aux_sym_instruction_list_repeat1,
    STATE(35), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [148] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(17), 1,
      anon_sym_height,
    ACTIONS(19), 1,
      anon_sym_label,
    ACTIONS(21), 1,
      anon_sym_const,
    ACTIONS(23), 1,
      anon_sym_heap,
    ACTIONS(25), 1,
      anon_sym_call,
    ACTIONS(27), 1,
      anon_sym_get,
    ACTIONS(29), 1,
      anon_sym_set,
    ACTIONS(31), 1,
      anon_sym_out,
    ACTIONS(33), 1,
      anon_sym_in,
    ACTIONS(35), 1,
      anon_sym_jump,
    ACTIONS(37), 1,
      anon_sym_branch,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_instruction_list_repeat1,
    STATE(4), 1,
      sym_comment,
    STATE(12), 1,
      sym__instruction,
    STATE(40), 1,
      sym_inst_label,
    STATE(35), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [223] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(5), 1,
      sym_comment,
    ACTIONS(84), 12,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
    ACTIONS(82), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [263] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(6), 1,
      sym_comment,
    ACTIONS(88), 9,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(86), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [300] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_comment,
    ACTIONS(92), 9,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(90), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [337] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(8), 1,
      sym_comment,
    ACTIONS(96), 9,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(94), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [374] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 1,
      sym_comment,
    ACTIONS(100), 8,
      anon_sym_LBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(98), 13,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [409] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(10), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(102), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [437] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(11), 1,
      sym_comment,
    ACTIONS(108), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(106), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [465] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(110), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [493] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(114), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [521] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(118), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [549] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(122), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [577] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(126), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [605] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(130), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [633] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(134), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [661] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(138), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [689] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(142), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [717] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(146), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [745] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(150), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [773] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(154), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [801] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(158), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [829] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(162), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [857] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(166), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [885] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(170), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [913] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(174), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [941] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(178), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [969] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(182), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [997] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(186), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1025] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(190), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1053] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(194), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1081] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(198), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1109] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(204), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(202), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1137] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(206), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1165] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(212), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(210), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1193] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym_comment,
    STATE(42), 1,
      aux_sym_array_repeat1,
    STATE(46), 1,
      sym__literal,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1231] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    ACTIONS(229), 1,
      aux_sym_number_token3,
    ACTIONS(232), 1,
      anon_sym_SQUOTE,
    ACTIONS(235), 1,
      anon_sym_AT,
    STATE(46), 1,
      sym__literal,
    STATE(39), 2,
      sym_comment,
      aux_sym_array_repeat1,
    ACTIONS(226), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1267] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(238), 1,
      sym_identifier,
    ACTIONS(240), 1,
      anon_sym_height,
    ACTIONS(242), 1,
      anon_sym_label,
    ACTIONS(244), 1,
      anon_sym_const,
    ACTIONS(246), 1,
      anon_sym_heap,
    ACTIONS(248), 1,
      anon_sym_call,
    ACTIONS(250), 1,
      anon_sym_get,
    ACTIONS(252), 1,
      anon_sym_set,
    ACTIONS(254), 1,
      anon_sym_out,
    ACTIONS(256), 1,
      anon_sym_in,
    ACTIONS(258), 1,
      anon_sym_jump,
    ACTIONS(260), 1,
      anon_sym_branch,
    STATE(40), 1,
      sym_comment,
  [1313] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_AT,
    ACTIONS(262), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_comment,
    STATE(94), 2,
      sym_array,
      sym__literal,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1349] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_AT,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      aux_sym_array_repeat1,
    STATE(42), 1,
      sym_comment,
    STATE(46), 1,
      sym__literal,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1387] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_AT,
    STATE(29), 1,
      sym__literal,
    STATE(43), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1419] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_AT,
    STATE(17), 1,
      sym__literal,
    STATE(44), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1451] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_comment,
    STATE(69), 1,
      sym_instruction_list,
    STATE(92), 1,
      sym_number,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1478] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(270), 1,
      aux_sym_number_token3,
    STATE(46), 1,
      sym_comment,
    ACTIONS(268), 6,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
  [1499] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(272), 1,
      ts_builtin_sym_end,
    ACTIONS(274), 1,
      anon_sym_func,
    ACTIONS(277), 1,
      anon_sym_inline,
    STATE(47), 2,
      sym_comment,
      aux_sym_source_file_repeat2,
    STATE(68), 2,
      sym_func,
      sym_inline,
  [1523] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(282), 1,
      anon_sym_func,
    ACTIONS(284), 1,
      anon_sym_inline,
    STATE(48), 1,
      sym_comment,
    STATE(50), 1,
      aux_sym_source_file_repeat2,
    STATE(68), 2,
      sym_func,
      sym_inline,
  [1549] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_entrypoint,
    STATE(41), 1,
      sym_data_label,
    STATE(49), 1,
      sym_comment,
    STATE(51), 1,
      sym_entrypoint,
    STATE(54), 1,
      aux_sym_source_file_repeat1,
    STATE(78), 1,
      sym_definition,
  [1577] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(282), 1,
      anon_sym_func,
    ACTIONS(284), 1,
      anon_sym_inline,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
    STATE(47), 1,
      aux_sym_source_file_repeat2,
    STATE(50), 1,
      sym_comment,
    STATE(68), 2,
      sym_func,
      sym_inline,
  [1603] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(282), 1,
      anon_sym_func,
    ACTIONS(284), 1,
      anon_sym_inline,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym_source_file_repeat2,
    STATE(68), 2,
      sym_func,
      sym_inline,
  [1629] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(282), 1,
      anon_sym_func,
    ACTIONS(284), 1,
      anon_sym_inline,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
    STATE(47), 1,
      aux_sym_source_file_repeat2,
    STATE(52), 1,
      sym_comment,
    STATE(68), 2,
      sym_func,
      sym_inline,
  [1655] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(20), 1,
      sym_number,
    STATE(53), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1676] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(290), 1,
      anon_sym_DOT,
    ACTIONS(293), 1,
      anon_sym_entrypoint,
    STATE(41), 1,
      sym_data_label,
    STATE(78), 1,
      sym_definition,
    STATE(54), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1699] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(27), 1,
      sym_number,
    STATE(55), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1720] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(25), 1,
      sym_number,
    STATE(56), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1741] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(21), 1,
      sym_number,
    STATE(57), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1762] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(58), 1,
      sym_comment,
    STATE(77), 1,
      sym_number,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1783] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(59), 1,
      sym_comment,
    STATE(76), 1,
      sym_number,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1804] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(23), 1,
      sym_number,
    STATE(60), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1825] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(13), 1,
      sym_number,
    STATE(61), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1846] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(34), 1,
      sym_number,
    STATE(62), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1867] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(63), 1,
      sym_comment,
    STATE(102), 1,
      sym_number,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1888] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_number_token3,
    STATE(24), 1,
      sym_number,
    STATE(64), 1,
      sym_comment,
    ACTIONS(216), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1909] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    ACTIONS(295), 1,
      anon_sym_PLUS,
    STATE(65), 1,
      sym_comment,
    STATE(70), 1,
      sym_instruction_list,
  [1928] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(66), 1,
      sym_comment,
    ACTIONS(297), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [1943] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(67), 1,
      sym_comment,
    ACTIONS(299), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [1958] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(68), 1,
      sym_comment,
    ACTIONS(301), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [1973] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(69), 1,
      sym_comment,
    ACTIONS(303), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [1988] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(70), 1,
      sym_comment,
    ACTIONS(305), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2003] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(71), 1,
      sym_comment,
    ACTIONS(307), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2018] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(72), 1,
      sym_comment,
    ACTIONS(309), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2033] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(73), 1,
      sym_comment,
    ACTIONS(311), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2048] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(313), 1,
      anon_sym_COLON,
    STATE(65), 1,
      sym_stack_behaviour,
    STATE(74), 1,
      sym_comment,
  [2064] = 4,
    ACTIONS(315), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(317), 1,
      anon_sym_SLASH_STAR,
    STATE(75), 1,
      sym_comment,
    ACTIONS(319), 2,
      sym_char,
      sym_char_escape,
  [2078] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(76), 1,
      sym_comment,
    ACTIONS(321), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [2092] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_instruction_list,
    STATE(77), 1,
      sym_comment,
  [2108] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(78), 1,
      sym_comment,
    ACTIONS(323), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2122] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(325), 1,
      anon_sym_PERCENT,
    STATE(19), 1,
      sym_port,
    STATE(79), 1,
      sym_comment,
  [2138] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(325), 1,
      anon_sym_PERCENT,
    STATE(16), 1,
      sym_port,
    STATE(80), 1,
      sym_comment,
  [2154] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(15), 1,
      sym_inst_label,
    STATE(81), 1,
      sym_comment,
  [2170] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(14), 1,
      sym_inst_label,
    STATE(82), 1,
      sym_comment,
  [2186] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(313), 1,
      anon_sym_COLON,
    STATE(83), 1,
      sym_comment,
    STATE(90), 1,
      sym_stack_behaviour,
  [2202] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(31), 1,
      sym_data_label,
    STATE(84), 1,
      sym_comment,
  [2218] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(85), 1,
      sym_comment,
    ACTIONS(327), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2232] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(86), 1,
      sym_comment,
    ACTIONS(329), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2246] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(37), 1,
      sym_inst_label,
    STATE(87), 1,
      sym_comment,
  [2262] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(33), 1,
      sym_inst_label,
    STATE(88), 1,
      sym_comment,
  [2278] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(325), 1,
      anon_sym_PERCENT,
    STATE(32), 1,
      sym_port,
    STATE(89), 1,
      sym_comment,
  [2294] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_instruction_list,
    STATE(90), 1,
      sym_comment,
  [2310] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(325), 1,
      anon_sym_PERCENT,
    STATE(28), 1,
      sym_port,
    STATE(91), 1,
      sym_comment,
  [2326] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_instruction_list,
    STATE(92), 1,
      sym_comment,
  [2342] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(18), 1,
      sym_data_label,
    STATE(93), 1,
      sym_comment,
  [2358] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(94), 1,
      sym_comment,
    ACTIONS(331), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2372] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(333), 1,
      anon_sym_SQUOTE,
    STATE(95), 1,
      sym_comment,
  [2385] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(335), 1,
      sym_function_name,
    STATE(96), 1,
      sym_comment,
  [2398] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(337), 1,
      sym_function_name,
    STATE(97), 1,
      sym_comment,
  [2411] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(339), 1,
      sym_identifier,
    STATE(98), 1,
      sym_comment,
  [2424] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(341), 1,
      sym_identifier,
    STATE(99), 1,
      sym_comment,
  [2437] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(343), 1,
      sym_function_name,
    STATE(100), 1,
      sym_comment,
  [2450] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(345), 1,
      anon_sym_SLASH,
    STATE(101), 1,
      sym_comment,
  [2463] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(347), 1,
      anon_sym_DASH_GT,
    STATE(102), 1,
      sym_comment,
  [2476] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(349), 1,
      ts_builtin_sym_end,
    STATE(103), 1,
      sym_comment,
  [2489] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(351), 1,
      sym_identifier,
    STATE(104), 1,
      sym_comment,
  [2502] = 4,
    ACTIONS(315), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(317), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(353), 1,
      aux_sym_comment_token2,
    STATE(105), 1,
      sym_comment,
  [2515] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(355), 1,
      sym_function_name,
    STATE(106), 1,
      sym_comment,
  [2528] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(357), 1,
      sym_identifier,
    STATE(107), 1,
      sym_comment,
  [2541] = 4,
    ACTIONS(315), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(317), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(359), 1,
      aux_sym_comment_token1,
    STATE(108), 1,
      sym_comment,
  [2554] = 1,
    ACTIONS(361), 1,
      ts_builtin_sym_end,
  [2558] = 1,
    ACTIONS(363), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 75,
  [SMALL_STATE(4)] = 148,
  [SMALL_STATE(5)] = 223,
  [SMALL_STATE(6)] = 263,
  [SMALL_STATE(7)] = 300,
  [SMALL_STATE(8)] = 337,
  [SMALL_STATE(9)] = 374,
  [SMALL_STATE(10)] = 409,
  [SMALL_STATE(11)] = 437,
  [SMALL_STATE(12)] = 465,
  [SMALL_STATE(13)] = 493,
  [SMALL_STATE(14)] = 521,
  [SMALL_STATE(15)] = 549,
  [SMALL_STATE(16)] = 577,
  [SMALL_STATE(17)] = 605,
  [SMALL_STATE(18)] = 633,
  [SMALL_STATE(19)] = 661,
  [SMALL_STATE(20)] = 689,
  [SMALL_STATE(21)] = 717,
  [SMALL_STATE(22)] = 745,
  [SMALL_STATE(23)] = 773,
  [SMALL_STATE(24)] = 801,
  [SMALL_STATE(25)] = 829,
  [SMALL_STATE(26)] = 857,
  [SMALL_STATE(27)] = 885,
  [SMALL_STATE(28)] = 913,
  [SMALL_STATE(29)] = 941,
  [SMALL_STATE(30)] = 969,
  [SMALL_STATE(31)] = 997,
  [SMALL_STATE(32)] = 1025,
  [SMALL_STATE(33)] = 1053,
  [SMALL_STATE(34)] = 1081,
  [SMALL_STATE(35)] = 1109,
  [SMALL_STATE(36)] = 1137,
  [SMALL_STATE(37)] = 1165,
  [SMALL_STATE(38)] = 1193,
  [SMALL_STATE(39)] = 1231,
  [SMALL_STATE(40)] = 1267,
  [SMALL_STATE(41)] = 1313,
  [SMALL_STATE(42)] = 1349,
  [SMALL_STATE(43)] = 1387,
  [SMALL_STATE(44)] = 1419,
  [SMALL_STATE(45)] = 1451,
  [SMALL_STATE(46)] = 1478,
  [SMALL_STATE(47)] = 1499,
  [SMALL_STATE(48)] = 1523,
  [SMALL_STATE(49)] = 1549,
  [SMALL_STATE(50)] = 1577,
  [SMALL_STATE(51)] = 1603,
  [SMALL_STATE(52)] = 1629,
  [SMALL_STATE(53)] = 1655,
  [SMALL_STATE(54)] = 1676,
  [SMALL_STATE(55)] = 1699,
  [SMALL_STATE(56)] = 1720,
  [SMALL_STATE(57)] = 1741,
  [SMALL_STATE(58)] = 1762,
  [SMALL_STATE(59)] = 1783,
  [SMALL_STATE(60)] = 1804,
  [SMALL_STATE(61)] = 1825,
  [SMALL_STATE(62)] = 1846,
  [SMALL_STATE(63)] = 1867,
  [SMALL_STATE(64)] = 1888,
  [SMALL_STATE(65)] = 1909,
  [SMALL_STATE(66)] = 1928,
  [SMALL_STATE(67)] = 1943,
  [SMALL_STATE(68)] = 1958,
  [SMALL_STATE(69)] = 1973,
  [SMALL_STATE(70)] = 1988,
  [SMALL_STATE(71)] = 2003,
  [SMALL_STATE(72)] = 2018,
  [SMALL_STATE(73)] = 2033,
  [SMALL_STATE(74)] = 2048,
  [SMALL_STATE(75)] = 2064,
  [SMALL_STATE(76)] = 2078,
  [SMALL_STATE(77)] = 2092,
  [SMALL_STATE(78)] = 2108,
  [SMALL_STATE(79)] = 2122,
  [SMALL_STATE(80)] = 2138,
  [SMALL_STATE(81)] = 2154,
  [SMALL_STATE(82)] = 2170,
  [SMALL_STATE(83)] = 2186,
  [SMALL_STATE(84)] = 2202,
  [SMALL_STATE(85)] = 2218,
  [SMALL_STATE(86)] = 2232,
  [SMALL_STATE(87)] = 2246,
  [SMALL_STATE(88)] = 2262,
  [SMALL_STATE(89)] = 2278,
  [SMALL_STATE(90)] = 2294,
  [SMALL_STATE(91)] = 2310,
  [SMALL_STATE(92)] = 2326,
  [SMALL_STATE(93)] = 2342,
  [SMALL_STATE(94)] = 2358,
  [SMALL_STATE(95)] = 2372,
  [SMALL_STATE(96)] = 2385,
  [SMALL_STATE(97)] = 2398,
  [SMALL_STATE(98)] = 2411,
  [SMALL_STATE(99)] = 2424,
  [SMALL_STATE(100)] = 2437,
  [SMALL_STATE(101)] = 2450,
  [SMALL_STATE(102)] = 2463,
  [SMALL_STATE(103)] = 2476,
  [SMALL_STATE(104)] = 2489,
  [SMALL_STATE(105)] = 2502,
  [SMALL_STATE(106)] = 2515,
  [SMALL_STATE(107)] = 2528,
  [SMALL_STATE(108)] = 2541,
  [SMALL_STATE(109)] = 2554,
  [SMALL_STATE(110)] = 2558,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(30),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(98),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(56),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(93),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(44),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(61),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(106),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(60),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(55),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(91),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(89),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(88),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(87),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_literal, 3, .production_id = 9),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char_literal, 3, .production_id = 9),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, .production_id = 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, .production_id = 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_label, 2, .production_id = 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_label, 2, .production_id = 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 6),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 6),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, .production_id = 10),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 10),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heap, 2, .production_id = 6),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heap, 2, .production_id = 6),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch, 3, .production_id = 10),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 3, .production_id = 10),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 3, .production_id = 10),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3, .production_id = 10),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in, 3, .production_id = 10),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in, 3, .production_id = 10),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const, 2, .production_id = 6),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 2, .production_id = 6),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, .production_id = 6),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, .production_id = 6),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out, 3, .production_id = 10),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out, 3, .production_id = 10),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3, .production_id = 10),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, .production_id = 10),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 3, .production_id = 10),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 3, .production_id = 10),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 2, .production_id = 7),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, .production_id = 7),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 2, .production_id = 6),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 2, .production_id = 6),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heap, 3, .production_id = 10),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heap, 3, .production_id = 10),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_height, 2, .production_id = 6),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_height, 2, .production_id = 6),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inst_label, 2, .production_id = 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inst_label, 2, .production_id = 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2, .production_id = 6),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, .production_id = 6),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out, 2, .production_id = 6),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out, 2, .production_id = 6),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const, 3, .production_id = 10),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 3, .production_id = 10),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 1, .production_id = 4),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, .production_id = 4),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 3, .production_id = 10),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 3, .production_id = 10),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in, 2, .production_id = 6),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in, 2, .production_id = 6),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 2, .production_id = 6),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2, .production_id = 6),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_height, 3, .production_id = 10),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_height, 3, .production_id = 10),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__instruction, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__instruction, 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port, 2, .production_id = 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port, 2, .production_id = 1),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch, 2, .production_id = 6),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 2, .production_id = 6),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [229] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(75),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(99),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(97),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(96),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(104),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_list, 2),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_list, 3, .production_id = 8),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entrypoint, 2, .production_id = 2),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4, .production_id = 11),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 4, .production_id = 11),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 6, .production_id = 13),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entrypoint, 3, .production_id = 5),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [317] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_behaviour, 4, .production_id = 12),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 2, .production_id = 3),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [345] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [349] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [353] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [359] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_URSL(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
