#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 118
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 13

enum {
  sym_identifier = 1,
  anon_sym_SLASH_SLASH = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_SLASH_STAR = 4,
  aux_sym_comment_token2 = 5,
  anon_sym_SLASH = 6,
  sym_function_name = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  aux_sym_number_token1 = 10,
  aux_sym_number_token2 = 11,
  aux_sym_number_token3 = 12,
  aux_sym_number_token4 = 13,
  anon_sym_SQUOTE = 14,
  sym_char = 15,
  sym_char_escape = 16,
  anon_sym_AT = 17,
  anon_sym_PERCENT = 18,
  anon_sym_COLON = 19,
  anon_sym_DOT = 20,
  anon_sym_DASH_GT = 21,
  anon_sym_entrypoint = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  anon_sym_func = 25,
  anon_sym_PLUS = 26,
  anon_sym_inline = 27,
  anon_sym_height = 28,
  anon_sym_label = 29,
  anon_sym_const = 30,
  anon_sym_heap = 31,
  anon_sym_call = 32,
  anon_sym_get = 33,
  anon_sym_set = 34,
  anon_sym_out = 35,
  anon_sym_in = 36,
  anon_sym_jump = 37,
  anon_sym_branch = 38,
  sym_source_file = 39,
  sym_comment = 40,
  sym_array = 41,
  sym__literal = 42,
  sym_number = 43,
  sym_char_literal = 44,
  sym_macro = 45,
  sym_port = 46,
  sym_inst_label = 47,
  sym_data_label = 48,
  sym_definition = 49,
  sym_stack_behaviour = 50,
  sym_instruction_list = 51,
  sym_entrypoint = 52,
  sym_func = 53,
  sym_inline = 54,
  sym__instruction = 55,
  sym_height = 56,
  sym_label = 57,
  sym_const = 58,
  sym_heap = 59,
  sym_call = 60,
  sym_get = 61,
  sym_set = 62,
  sym_out = 63,
  sym_in = 64,
  sym_jump = 65,
  sym_branch = 66,
  sym_instruction = 67,
  aux_sym_source_file_repeat1 = 68,
  aux_sym_source_file_repeat2 = 69,
  aux_sym_array_repeat1 = 70,
  aux_sym_instruction_list_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [sym_function_name] = "function_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [anon_sym_SQUOTE] = "'",
  [sym_char] = "char",
  [sym_char_escape] = "char_escape",
  [anon_sym_AT] = "@",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_entrypoint] = "entrypoint",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_func] = "func",
  [anon_sym_PLUS] = "+",
  [anon_sym_inline] = "inline",
  [anon_sym_height] = "height",
  [anon_sym_label] = "label",
  [anon_sym_const] = "const",
  [anon_sym_heap] = "heap",
  [anon_sym_call] = "call",
  [anon_sym_get] = "get",
  [anon_sym_set] = "set",
  [anon_sym_out] = "out",
  [anon_sym_in] = "in",
  [anon_sym_jump] = "jump",
  [anon_sym_branch] = "branch",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_array] = "array",
  [sym__literal] = "_literal",
  [sym_number] = "number",
  [sym_char_literal] = "char_literal",
  [sym_macro] = "macro",
  [sym_port] = "port",
  [sym_inst_label] = "inst_label",
  [sym_data_label] = "data_label",
  [sym_definition] = "definition",
  [sym_stack_behaviour] = "stack_behaviour",
  [sym_instruction_list] = "instruction_list",
  [sym_entrypoint] = "entrypoint",
  [sym_func] = "func",
  [sym_inline] = "inline",
  [sym__instruction] = "_instruction",
  [sym_height] = "height",
  [sym_label] = "label",
  [sym_const] = "const",
  [sym_heap] = "heap",
  [sym_call] = "call",
  [sym_get] = "get",
  [sym_set] = "set",
  [sym_out] = "out",
  [sym_in] = "in",
  [sym_jump] = "jump",
  [sym_branch] = "branch",
  [sym_instruction] = "instruction",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_instruction_list_repeat1] = "instruction_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_function_name] = sym_function_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_char] = sym_char,
  [sym_char_escape] = sym_char_escape,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_entrypoint] = anon_sym_entrypoint,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_inline] = anon_sym_inline,
  [anon_sym_height] = anon_sym_height,
  [anon_sym_label] = anon_sym_label,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_heap] = anon_sym_heap,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_branch] = anon_sym_branch,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_array] = sym_array,
  [sym__literal] = sym__literal,
  [sym_number] = sym_number,
  [sym_char_literal] = sym_char_literal,
  [sym_macro] = sym_macro,
  [sym_port] = sym_port,
  [sym_inst_label] = sym_inst_label,
  [sym_data_label] = sym_data_label,
  [sym_definition] = sym_definition,
  [sym_stack_behaviour] = sym_stack_behaviour,
  [sym_instruction_list] = sym_instruction_list,
  [sym_entrypoint] = sym_entrypoint,
  [sym_func] = sym_func,
  [sym_inline] = sym_inline,
  [sym__instruction] = sym__instruction,
  [sym_height] = sym_height,
  [sym_label] = sym_label,
  [sym_const] = sym_const,
  [sym_heap] = sym_heap,
  [sym_call] = sym_call,
  [sym_get] = sym_get,
  [sym_set] = sym_set,
  [sym_out] = sym_out,
  [sym_in] = sym_in,
  [sym_jump] = sym_jump,
  [sym_branch] = sym_branch,
  [sym_instruction] = sym_instruction,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_instruction_list_repeat1] = aux_sym_instruction_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_char_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entrypoint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_height] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_label] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_heap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_port] = {
    .visible = true,
    .named = true,
  },
  [sym_inst_label] = {
    .visible = true,
    .named = true,
  },
  [sym_data_label] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_behaviour] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction_list] = {
    .visible = true,
    .named = true,
  },
  [sym_entrypoint] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_height] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_heap] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_get] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_out] = {
    .visible = true,
    .named = true,
  },
  [sym_in] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_instruction = 1,
  field_label = 2,
  field_locals = 3,
  field_name = 4,
  field_opcode = 5,
  field_operand = 6,
  field_params = 7,
  field_returns = 8,
  field_stack = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_instruction] = "instruction",
  [field_label] = "label",
  [field_locals] = "locals",
  [field_name] = "name",
  [field_opcode] = "opcode",
  [field_operand] = "operand",
  [field_params] = "params",
  [field_returns] = "returns",
  [field_stack] = "stack",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 3},
  [12] = {.index = 18, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_label, 0},
    {field_value, 1},
  [3] =
    {field_opcode, 0},
  [4] =
    {field_operand, 1},
  [5] =
    {field_label, 0},
    {field_opcode, 1},
  [7] =
    {field_instruction, 2},
  [8] =
    {field_value, 1},
  [9] =
    {field_label, 0},
    {field_operand, 2},
  [11] =
    {field_instruction, 3},
    {field_locals, 1},
  [13] =
    {field_params, 1},
    {field_returns, 3},
  [15] =
    {field_instruction, 4},
    {field_name, 1},
    {field_stack, 2},
  [18] =
    {field_instruction, 6},
    {field_locals, 4},
    {field_name, 1},
    {field_stack, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '$') ADVANCE(10);
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '+') ADVANCE(44);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '0') ADVANCE(29);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(36);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_function_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_char_escape);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'g') ADVANCE(5);
      if (lookahead == 'h') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'j') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 21:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 28:
      if (lookahead == 'c') ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 31:
      if (lookahead == 'g') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'y') ADVANCE(49);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_heap);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'h') ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_label);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_height);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_inline);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_entrypoint);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 16},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 0},
  [116] = {(TSStateId)(-1)},
  [117] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_function_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_char_escape] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_entrypoint] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_inline] = ACTIONS(1),
    [anon_sym_height] = ACTIONS(1),
    [anon_sym_label] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_heap] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(102),
    [sym_comment] = STATE(1),
    [sym_data_label] = STATE(46),
    [sym_definition] = STATE(92),
    [sym_entrypoint] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(54),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_entrypoint] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_height,
    ACTIONS(17), 1,
      anon_sym_label,
    ACTIONS(19), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_heap,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_out,
    ACTIONS(31), 1,
      anon_sym_in,
    ACTIONS(33), 1,
      anon_sym_jump,
    ACTIONS(35), 1,
      anon_sym_branch,
    STATE(2), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_instruction_list_repeat1,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(113), 1,
      sym_instruction_list,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [75] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_height,
    ACTIONS(17), 1,
      anon_sym_label,
    ACTIONS(19), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_heap,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_out,
    ACTIONS(31), 1,
      anon_sym_in,
    ACTIONS(33), 1,
      anon_sym_jump,
    ACTIONS(35), 1,
      anon_sym_branch,
    STATE(3), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_instruction_list_repeat1,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(111), 1,
      sym_instruction_list,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [150] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_height,
    ACTIONS(17), 1,
      anon_sym_label,
    ACTIONS(19), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_heap,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_out,
    ACTIONS(31), 1,
      anon_sym_in,
    ACTIONS(33), 1,
      anon_sym_jump,
    ACTIONS(35), 1,
      anon_sym_branch,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_instruction_list_repeat1,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(109), 1,
      sym_instruction_list,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [225] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_height,
    ACTIONS(17), 1,
      anon_sym_label,
    ACTIONS(19), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_heap,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_out,
    ACTIONS(31), 1,
      anon_sym_in,
    ACTIONS(33), 1,
      anon_sym_jump,
    ACTIONS(35), 1,
      anon_sym_branch,
    STATE(5), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_instruction_list_repeat1,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(115), 1,
      sym_instruction_list,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [300] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_height,
    ACTIONS(17), 1,
      anon_sym_label,
    ACTIONS(19), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_heap,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_out,
    ACTIONS(31), 1,
      anon_sym_in,
    ACTIONS(33), 1,
      anon_sym_jump,
    ACTIONS(35), 1,
      anon_sym_branch,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_instruction_list_repeat1,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [375] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      anon_sym_height,
    ACTIONS(50), 1,
      anon_sym_label,
    ACTIONS(53), 1,
      anon_sym_const,
    ACTIONS(56), 1,
      anon_sym_heap,
    ACTIONS(59), 1,
      anon_sym_call,
    ACTIONS(62), 1,
      anon_sym_get,
    ACTIONS(65), 1,
      anon_sym_set,
    ACTIONS(68), 1,
      anon_sym_out,
    ACTIONS(71), 1,
      anon_sym_in,
    ACTIONS(74), 1,
      anon_sym_jump,
    ACTIONS(77), 1,
      anon_sym_branch,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(7), 2,
      sym_comment,
      aux_sym_instruction_list_repeat1,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [448] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_COLON,
    ACTIONS(15), 1,
      anon_sym_height,
    ACTIONS(17), 1,
      anon_sym_label,
    ACTIONS(19), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_heap,
    ACTIONS(23), 1,
      anon_sym_call,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_out,
    ACTIONS(31), 1,
      anon_sym_in,
    ACTIONS(33), 1,
      anon_sym_jump,
    ACTIONS(35), 1,
      anon_sym_branch,
    STATE(6), 1,
      aux_sym_instruction_list_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(38), 1,
      sym__instruction,
    STATE(43), 1,
      sym_inst_label,
    STATE(108), 1,
      sym_instruction_list,
    STATE(39), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [523] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 1,
      sym_comment,
    ACTIONS(82), 12,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
    ACTIONS(80), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [563] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(10), 1,
      sym_comment,
    ACTIONS(86), 9,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(84), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [600] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(11), 1,
      sym_comment,
    ACTIONS(90), 9,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(88), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [637] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(94), 9,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(92), 14,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_entrypoint,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [674] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(98), 8,
      anon_sym_LBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(96), 13,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [709] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(100), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [737] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(104), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [765] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(108), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [793] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(112), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [821] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(116), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [849] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(120), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [877] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(124), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [905] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(128), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [933] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(132), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [961] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(136), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [989] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(140), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1017] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(144), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1045] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(148), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1073] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(154), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(152), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1101] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(158), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(156), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1129] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(162), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(160), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1157] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(164), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1185] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(170), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(168), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1213] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(174), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(172), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1241] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(178), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(176), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1269] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(180), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1297] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(186), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(184), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1325] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(190), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(188), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1353] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(194), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(192), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1381] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(198), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(196), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1409] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(200), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1437] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(206), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(204), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1465] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(210), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(208), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1493] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
    ACTIONS(217), 1,
      aux_sym_number_token3,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    ACTIONS(223), 1,
      anon_sym_AT,
    STATE(49), 1,
      sym__literal,
    STATE(42), 2,
      sym_comment,
      aux_sym_array_repeat1,
    ACTIONS(214), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(12), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1529] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(226), 1,
      sym_identifier,
    ACTIONS(228), 1,
      anon_sym_height,
    ACTIONS(230), 1,
      anon_sym_label,
    ACTIONS(232), 1,
      anon_sym_const,
    ACTIONS(234), 1,
      anon_sym_heap,
    ACTIONS(236), 1,
      anon_sym_call,
    ACTIONS(238), 1,
      anon_sym_get,
    ACTIONS(240), 1,
      anon_sym_set,
    ACTIONS(242), 1,
      anon_sym_out,
    ACTIONS(244), 1,
      anon_sym_in,
    ACTIONS(246), 1,
      anon_sym_jump,
    ACTIONS(248), 1,
      anon_sym_branch,
    STATE(43), 1,
      sym_comment,
  [1575] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_AT,
    STATE(44), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_array_repeat1,
    STATE(49), 1,
      sym__literal,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(12), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1613] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_AT,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_array_repeat1,
    STATE(45), 1,
      sym_comment,
    STATE(49), 1,
      sym__literal,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(12), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1651] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_AT,
    ACTIONS(262), 1,
      anon_sym_LBRACK,
    STATE(46), 1,
      sym_comment,
    STATE(91), 2,
      sym_array,
      sym__literal,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(12), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1687] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_AT,
    STATE(19), 1,
      sym__literal,
    STATE(47), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(12), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1719] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_AT,
    STATE(34), 1,
      sym__literal,
    STATE(48), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(12), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1751] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(266), 1,
      aux_sym_number_token3,
    STATE(49), 1,
      sym_comment,
    ACTIONS(264), 6,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
  [1772] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
    ACTIONS(270), 1,
      anon_sym_func,
    ACTIONS(272), 1,
      anon_sym_inline,
    STATE(50), 1,
      sym_comment,
    STATE(56), 1,
      aux_sym_source_file_repeat2,
    STATE(71), 2,
      sym_func,
      sym_inline,
  [1798] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(270), 1,
      anon_sym_func,
    ACTIONS(272), 1,
      anon_sym_inline,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym_comment,
    STATE(56), 1,
      aux_sym_source_file_repeat2,
    STATE(71), 2,
      sym_func,
      sym_inline,
  [1824] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(270), 1,
      anon_sym_func,
    ACTIONS(272), 1,
      anon_sym_inline,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      aux_sym_source_file_repeat2,
    STATE(52), 1,
      sym_comment,
    STATE(71), 2,
      sym_func,
      sym_inline,
  [1850] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_comment,
    STATE(105), 1,
      sym_number,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1874] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_entrypoint,
    STATE(46), 1,
      sym_data_label,
    STATE(52), 1,
      sym_entrypoint,
    STATE(54), 1,
      sym_comment,
    STATE(64), 1,
      aux_sym_source_file_repeat1,
    STATE(92), 1,
      sym_definition,
  [1902] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(270), 1,
      anon_sym_func,
    ACTIONS(272), 1,
      anon_sym_inline,
    ACTIONS(278), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      aux_sym_source_file_repeat2,
    STATE(55), 1,
      sym_comment,
    STATE(71), 2,
      sym_func,
      sym_inline,
  [1928] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(282), 1,
      anon_sym_func,
    ACTIONS(285), 1,
      anon_sym_inline,
    STATE(56), 2,
      sym_comment,
      aux_sym_source_file_repeat2,
    STATE(71), 2,
      sym_func,
      sym_inline,
  [1952] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(31), 1,
      sym_number,
    STATE(57), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1973] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(30), 1,
      sym_number,
    STATE(58), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1994] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(33), 1,
      sym_number,
    STATE(59), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2015] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(60), 1,
      sym_comment,
    STATE(110), 1,
      sym_number,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2036] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(61), 1,
      sym_comment,
    STATE(104), 1,
      sym_number,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2057] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(36), 1,
      sym_number,
    STATE(62), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2078] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(14), 1,
      sym_number,
    STATE(63), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2099] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(288), 1,
      anon_sym_DOT,
    ACTIONS(291), 1,
      anon_sym_entrypoint,
    STATE(46), 1,
      sym_data_label,
    STATE(92), 1,
      sym_definition,
    STATE(64), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [2122] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(65), 1,
      sym_comment,
    STATE(86), 1,
      sym_number,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2143] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(21), 1,
      sym_number,
    STATE(66), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2164] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(16), 1,
      sym_number,
    STATE(67), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2185] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_number_token3,
    STATE(18), 1,
      sym_number,
    STATE(68), 1,
      sym_comment,
    ACTIONS(252), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [2206] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(69), 1,
      sym_comment,
    ACTIONS(293), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2221] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(70), 1,
      sym_comment,
    ACTIONS(295), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2236] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(71), 1,
      sym_comment,
    ACTIONS(297), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2251] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(72), 1,
      sym_comment,
    ACTIONS(299), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2266] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(73), 1,
      sym_comment,
    ACTIONS(301), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2281] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(74), 1,
      sym_comment,
    ACTIONS(303), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inline,
  [2296] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(305), 1,
      anon_sym_PERCENT,
    STATE(40), 1,
      sym_port,
    STATE(75), 1,
      sym_comment,
  [2312] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(35), 1,
      sym_data_label,
    STATE(76), 1,
      sym_comment,
  [2328] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_DOT,
    STATE(20), 1,
      sym_data_label,
    STATE(77), 1,
      sym_comment,
  [2344] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(305), 1,
      anon_sym_PERCENT,
    STATE(15), 1,
      sym_port,
    STATE(78), 1,
      sym_comment,
  [2360] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(305), 1,
      anon_sym_PERCENT,
    STATE(27), 1,
      sym_port,
    STATE(79), 1,
      sym_comment,
  [2376] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(41), 1,
      sym_inst_label,
    STATE(80), 1,
      sym_comment,
  [2392] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(23), 1,
      sym_inst_label,
    STATE(81), 1,
      sym_comment,
  [2408] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(305), 1,
      anon_sym_PERCENT,
    STATE(28), 1,
      sym_port,
    STATE(82), 1,
      sym_comment,
  [2424] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(26), 1,
      sym_inst_label,
    STATE(83), 1,
      sym_comment,
  [2440] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_COLON,
    STATE(25), 1,
      sym_inst_label,
    STATE(84), 1,
      sym_comment,
  [2456] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(85), 1,
      sym_comment,
    ACTIONS(307), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2470] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(86), 1,
      sym_comment,
    ACTIONS(309), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [2484] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(87), 1,
      sym_comment,
    ACTIONS(311), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2498] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(313), 1,
      anon_sym_COLON,
    STATE(88), 1,
      sym_comment,
    STATE(89), 1,
      sym_stack_behaviour,
  [2514] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(315), 1,
      anon_sym_LBRACE,
    ACTIONS(317), 1,
      anon_sym_PLUS,
    STATE(89), 1,
      sym_comment,
  [2530] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(313), 1,
      anon_sym_COLON,
    STATE(90), 1,
      sym_comment,
    STATE(103), 1,
      sym_stack_behaviour,
  [2546] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(91), 1,
      sym_comment,
    ACTIONS(319), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2560] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(92), 1,
      sym_comment,
    ACTIONS(321), 2,
      anon_sym_DOT,
      anon_sym_entrypoint,
  [2574] = 4,
    ACTIONS(323), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(325), 1,
      anon_sym_SLASH_STAR,
    STATE(93), 1,
      sym_comment,
    ACTIONS(327), 2,
      sym_char,
      sym_char_escape,
  [2588] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(329), 1,
      sym_function_name,
    STATE(94), 1,
      sym_comment,
  [2601] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(331), 1,
      anon_sym_SQUOTE,
    STATE(95), 1,
      sym_comment,
  [2614] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(333), 1,
      anon_sym_SLASH,
    STATE(96), 1,
      sym_comment,
  [2627] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(335), 1,
      sym_identifier,
    STATE(97), 1,
      sym_comment,
  [2640] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(337), 1,
      sym_function_name,
    STATE(98), 1,
      sym_comment,
  [2653] = 4,
    ACTIONS(323), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(325), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(339), 1,
      aux_sym_comment_token1,
    STATE(99), 1,
      sym_comment,
  [2666] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(341), 1,
      sym_function_name,
    STATE(100), 1,
      sym_comment,
  [2679] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(343), 1,
      sym_identifier,
    STATE(101), 1,
      sym_comment,
  [2692] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(345), 1,
      ts_builtin_sym_end,
    STATE(102), 1,
      sym_comment,
  [2705] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(347), 1,
      anon_sym_LBRACE,
    STATE(103), 1,
      sym_comment,
  [2718] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(349), 1,
      anon_sym_DASH_GT,
    STATE(104), 1,
      sym_comment,
  [2731] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(351), 1,
      anon_sym_LBRACE,
    STATE(105), 1,
      sym_comment,
  [2744] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(353), 1,
      sym_identifier,
    STATE(106), 1,
      sym_comment,
  [2757] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(355), 1,
      sym_identifier,
    STATE(107), 1,
      sym_comment,
  [2770] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
    STATE(108), 1,
      sym_comment,
  [2783] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(359), 1,
      anon_sym_RBRACE,
    STATE(109), 1,
      sym_comment,
  [2796] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(361), 1,
      anon_sym_LBRACE,
    STATE(110), 1,
      sym_comment,
  [2809] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(363), 1,
      anon_sym_RBRACE,
    STATE(111), 1,
      sym_comment,
  [2822] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(365), 1,
      sym_function_name,
    STATE(112), 1,
      sym_comment,
  [2835] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(367), 1,
      anon_sym_RBRACE,
    STATE(113), 1,
      sym_comment,
  [2848] = 4,
    ACTIONS(323), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(325), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(369), 1,
      aux_sym_comment_token2,
    STATE(114), 1,
      sym_comment,
  [2861] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(371), 1,
      anon_sym_RBRACE,
    STATE(115), 1,
      sym_comment,
  [2874] = 1,
    ACTIONS(373), 1,
      ts_builtin_sym_end,
  [2878] = 1,
    ACTIONS(375), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 75,
  [SMALL_STATE(4)] = 150,
  [SMALL_STATE(5)] = 225,
  [SMALL_STATE(6)] = 300,
  [SMALL_STATE(7)] = 375,
  [SMALL_STATE(8)] = 448,
  [SMALL_STATE(9)] = 523,
  [SMALL_STATE(10)] = 563,
  [SMALL_STATE(11)] = 600,
  [SMALL_STATE(12)] = 637,
  [SMALL_STATE(13)] = 674,
  [SMALL_STATE(14)] = 709,
  [SMALL_STATE(15)] = 737,
  [SMALL_STATE(16)] = 765,
  [SMALL_STATE(17)] = 793,
  [SMALL_STATE(18)] = 821,
  [SMALL_STATE(19)] = 849,
  [SMALL_STATE(20)] = 877,
  [SMALL_STATE(21)] = 905,
  [SMALL_STATE(22)] = 933,
  [SMALL_STATE(23)] = 961,
  [SMALL_STATE(24)] = 989,
  [SMALL_STATE(25)] = 1017,
  [SMALL_STATE(26)] = 1045,
  [SMALL_STATE(27)] = 1073,
  [SMALL_STATE(28)] = 1101,
  [SMALL_STATE(29)] = 1129,
  [SMALL_STATE(30)] = 1157,
  [SMALL_STATE(31)] = 1185,
  [SMALL_STATE(32)] = 1213,
  [SMALL_STATE(33)] = 1241,
  [SMALL_STATE(34)] = 1269,
  [SMALL_STATE(35)] = 1297,
  [SMALL_STATE(36)] = 1325,
  [SMALL_STATE(37)] = 1353,
  [SMALL_STATE(38)] = 1381,
  [SMALL_STATE(39)] = 1409,
  [SMALL_STATE(40)] = 1437,
  [SMALL_STATE(41)] = 1465,
  [SMALL_STATE(42)] = 1493,
  [SMALL_STATE(43)] = 1529,
  [SMALL_STATE(44)] = 1575,
  [SMALL_STATE(45)] = 1613,
  [SMALL_STATE(46)] = 1651,
  [SMALL_STATE(47)] = 1687,
  [SMALL_STATE(48)] = 1719,
  [SMALL_STATE(49)] = 1751,
  [SMALL_STATE(50)] = 1772,
  [SMALL_STATE(51)] = 1798,
  [SMALL_STATE(52)] = 1824,
  [SMALL_STATE(53)] = 1850,
  [SMALL_STATE(54)] = 1874,
  [SMALL_STATE(55)] = 1902,
  [SMALL_STATE(56)] = 1928,
  [SMALL_STATE(57)] = 1952,
  [SMALL_STATE(58)] = 1973,
  [SMALL_STATE(59)] = 1994,
  [SMALL_STATE(60)] = 2015,
  [SMALL_STATE(61)] = 2036,
  [SMALL_STATE(62)] = 2057,
  [SMALL_STATE(63)] = 2078,
  [SMALL_STATE(64)] = 2099,
  [SMALL_STATE(65)] = 2122,
  [SMALL_STATE(66)] = 2143,
  [SMALL_STATE(67)] = 2164,
  [SMALL_STATE(68)] = 2185,
  [SMALL_STATE(69)] = 2206,
  [SMALL_STATE(70)] = 2221,
  [SMALL_STATE(71)] = 2236,
  [SMALL_STATE(72)] = 2251,
  [SMALL_STATE(73)] = 2266,
  [SMALL_STATE(74)] = 2281,
  [SMALL_STATE(75)] = 2296,
  [SMALL_STATE(76)] = 2312,
  [SMALL_STATE(77)] = 2328,
  [SMALL_STATE(78)] = 2344,
  [SMALL_STATE(79)] = 2360,
  [SMALL_STATE(80)] = 2376,
  [SMALL_STATE(81)] = 2392,
  [SMALL_STATE(82)] = 2408,
  [SMALL_STATE(83)] = 2424,
  [SMALL_STATE(84)] = 2440,
  [SMALL_STATE(85)] = 2456,
  [SMALL_STATE(86)] = 2470,
  [SMALL_STATE(87)] = 2484,
  [SMALL_STATE(88)] = 2498,
  [SMALL_STATE(89)] = 2514,
  [SMALL_STATE(90)] = 2530,
  [SMALL_STATE(91)] = 2546,
  [SMALL_STATE(92)] = 2560,
  [SMALL_STATE(93)] = 2574,
  [SMALL_STATE(94)] = 2588,
  [SMALL_STATE(95)] = 2601,
  [SMALL_STATE(96)] = 2614,
  [SMALL_STATE(97)] = 2627,
  [SMALL_STATE(98)] = 2640,
  [SMALL_STATE(99)] = 2653,
  [SMALL_STATE(100)] = 2666,
  [SMALL_STATE(101)] = 2679,
  [SMALL_STATE(102)] = 2692,
  [SMALL_STATE(103)] = 2705,
  [SMALL_STATE(104)] = 2718,
  [SMALL_STATE(105)] = 2731,
  [SMALL_STATE(106)] = 2744,
  [SMALL_STATE(107)] = 2757,
  [SMALL_STATE(108)] = 2770,
  [SMALL_STATE(109)] = 2783,
  [SMALL_STATE(110)] = 2796,
  [SMALL_STATE(111)] = 2809,
  [SMALL_STATE(112)] = 2822,
  [SMALL_STATE(113)] = 2835,
  [SMALL_STATE(114)] = 2848,
  [SMALL_STATE(115)] = 2861,
  [SMALL_STATE(116)] = 2874,
  [SMALL_STATE(117)] = 2878,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_list, 1),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(29),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(97),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 2),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(62),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(76),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(48),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(59),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(98),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(57),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(58),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(82),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(78),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(83),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(84),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, .production_id = 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_literal, 3, .production_id = 7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char_literal, 3, .production_id = 7),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_label, 2, .production_id = 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_label, 2, .production_id = 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 3, .production_id = 8),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 3, .production_id = 8),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in, 2, .production_id = 4),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in, 2, .production_id = 4),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3, .production_id = 8),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, .production_id = 8),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, .production_id = 8),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 8),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heap, 3, .production_id = 8),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heap, 3, .production_id = 8),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const, 3, .production_id = 8),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 3, .production_id = 8),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 3, .production_id = 8),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 3, .production_id = 8),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_height, 3, .production_id = 8),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_height, 3, .production_id = 8),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port, 2, .production_id = 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port, 2, .production_id = 1),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch, 3, .production_id = 8),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 3, .production_id = 8),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 2, .production_id = 5),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, .production_id = 5),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch, 2, .production_id = 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 2, .production_id = 4),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 2, .production_id = 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2, .production_id = 4),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out, 3, .production_id = 8),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out, 3, .production_id = 8),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out, 2, .production_id = 4),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out, 2, .production_id = 4),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 1, .production_id = 3),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, .production_id = 3),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2, .production_id = 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, .production_id = 4),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 2, .production_id = 4),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 2, .production_id = 4),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 4),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heap, 2, .production_id = 4),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heap, 2, .production_id = 4),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const, 2, .production_id = 4),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 2, .production_id = 4),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, .production_id = 4),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, .production_id = 4),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_height, 2, .production_id = 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_height, 2, .production_id = 4),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inst_label, 2, .production_id = 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inst_label, 2, .production_id = 1),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 1),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__instruction, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__instruction, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in, 3, .production_id = 8),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in, 3, .production_id = 8),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 3, .production_id = 8),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3, .production_id = 8),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(9),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(9),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(93),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(101),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(112),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(94),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(107),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entrypoint, 5, .production_id = 9),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 8, .production_id = 12),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entrypoint, 4, .production_id = 6),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 6, .production_id = 11),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 6, .production_id = 11),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_behaviour, 4, .production_id = 10),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 2, .production_id = 2),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [345] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [369] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_URSL(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
