#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 13

enum {
  sym_identifier = 1,
  anon_sym_SLASH_SLASH = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_SLASH_STAR = 4,
  aux_sym_comment_token2 = 5,
  anon_sym_SLASH = 6,
  sym_function_name = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  aux_sym_number_token1 = 10,
  aux_sym_number_token2 = 11,
  aux_sym_number_token3 = 12,
  aux_sym_number_token4 = 13,
  anon_sym_SQUOTE = 14,
  sym_char = 15,
  sym_char_escape = 16,
  anon_sym_AT = 17,
  anon_sym_PERCENT = 18,
  anon_sym_COLON = 19,
  anon_sym_DOT = 20,
  anon_sym_DASH_GT = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_func = 24,
  anon_sym_PLUS = 25,
  anon_sym_inst = 26,
  anon_sym_height = 27,
  anon_sym_label = 28,
  anon_sym_const = 29,
  anon_sym_heap = 30,
  anon_sym_call = 31,
  anon_sym_get = 32,
  anon_sym_set = 33,
  anon_sym_out = 34,
  anon_sym_in = 35,
  anon_sym_jump = 36,
  anon_sym_branch = 37,
  sym_source_file = 38,
  sym_comment = 39,
  sym_array = 40,
  sym__literal = 41,
  sym_number = 42,
  sym_char_literal = 43,
  sym_macro = 44,
  sym_port = 45,
  sym_inst_label = 46,
  sym_data_label = 47,
  sym_definition = 48,
  sym_stack_behaviour = 49,
  sym_instruction_list = 50,
  sym_func = 51,
  sym_custom_instruction = 52,
  sym__instruction = 53,
  sym_height = 54,
  sym_label = 55,
  sym_const = 56,
  sym_heap = 57,
  sym_call = 58,
  sym_get = 59,
  sym_set = 60,
  sym_out = 61,
  sym_in = 62,
  sym_jump = 63,
  sym_branch = 64,
  sym_instruction = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_source_file_repeat2 = 67,
  aux_sym_array_repeat1 = 68,
  aux_sym_instruction_list_repeat1 = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [sym_function_name] = "function_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [anon_sym_SQUOTE] = "'",
  [sym_char] = "char",
  [sym_char_escape] = "char_escape",
  [anon_sym_AT] = "@",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_func] = "func",
  [anon_sym_PLUS] = "+",
  [anon_sym_inst] = "inst",
  [anon_sym_height] = "height",
  [anon_sym_label] = "label",
  [anon_sym_const] = "const",
  [anon_sym_heap] = "heap",
  [anon_sym_call] = "call",
  [anon_sym_get] = "get",
  [anon_sym_set] = "set",
  [anon_sym_out] = "out",
  [anon_sym_in] = "in",
  [anon_sym_jump] = "jump",
  [anon_sym_branch] = "branch",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_array] = "array",
  [sym__literal] = "_literal",
  [sym_number] = "number",
  [sym_char_literal] = "char_literal",
  [sym_macro] = "macro",
  [sym_port] = "port",
  [sym_inst_label] = "inst_label",
  [sym_data_label] = "data_label",
  [sym_definition] = "definition",
  [sym_stack_behaviour] = "stack_behaviour",
  [sym_instruction_list] = "instruction_list",
  [sym_func] = "func",
  [sym_custom_instruction] = "custom_instruction",
  [sym__instruction] = "_instruction",
  [sym_height] = "height",
  [sym_label] = "label",
  [sym_const] = "const",
  [sym_heap] = "heap",
  [sym_call] = "call",
  [sym_get] = "get",
  [sym_set] = "set",
  [sym_out] = "out",
  [sym_in] = "in",
  [sym_jump] = "jump",
  [sym_branch] = "branch",
  [sym_instruction] = "instruction",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_instruction_list_repeat1] = "instruction_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_function_name] = sym_function_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_char] = sym_char,
  [sym_char_escape] = sym_char_escape,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_inst] = anon_sym_inst,
  [anon_sym_height] = anon_sym_height,
  [anon_sym_label] = anon_sym_label,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_heap] = anon_sym_heap,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_branch] = anon_sym_branch,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_array] = sym_array,
  [sym__literal] = sym__literal,
  [sym_number] = sym_number,
  [sym_char_literal] = sym_char_literal,
  [sym_macro] = sym_macro,
  [sym_port] = sym_port,
  [sym_inst_label] = sym_inst_label,
  [sym_data_label] = sym_data_label,
  [sym_definition] = sym_definition,
  [sym_stack_behaviour] = sym_stack_behaviour,
  [sym_instruction_list] = sym_instruction_list,
  [sym_func] = sym_func,
  [sym_custom_instruction] = sym_custom_instruction,
  [sym__instruction] = sym__instruction,
  [sym_height] = sym_height,
  [sym_label] = sym_label,
  [sym_const] = sym_const,
  [sym_heap] = sym_heap,
  [sym_call] = sym_call,
  [sym_get] = sym_get,
  [sym_set] = sym_set,
  [sym_out] = sym_out,
  [sym_in] = sym_in,
  [sym_jump] = sym_jump,
  [sym_branch] = sym_branch,
  [sym_instruction] = sym_instruction,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_instruction_list_repeat1] = aux_sym_instruction_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_char_escape] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_height] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_label] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_heap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_port] = {
    .visible = true,
    .named = true,
  },
  [sym_inst_label] = {
    .visible = true,
    .named = true,
  },
  [sym_data_label] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_stack_behaviour] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction_list] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_custom_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_height] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_heap] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_get] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_out] = {
    .visible = true,
    .named = true,
  },
  [sym_in] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_instructions = 1,
  field_label = 2,
  field_locals = 3,
  field_name = 4,
  field_opcode = 5,
  field_operand = 6,
  field_params = 7,
  field_returns = 8,
  field_stack = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_instructions] = "instructions",
  [field_label] = "label",
  [field_locals] = "locals",
  [field_name] = "name",
  [field_opcode] = "opcode",
  [field_operand] = "operand",
  [field_params] = "params",
  [field_returns] = "returns",
  [field_stack] = "stack",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_label, 0},
    {field_value, 1},
  [3] =
    {field_instructions, 2},
    {field_name, 1},
  [5] =
    {field_opcode, 0},
  [6] =
    {field_instructions, 3},
    {field_name, 1},
    {field_stack, 2},
  [9] =
    {field_value, 1},
  [10] =
    {field_operand, 1},
  [11] =
    {field_label, 0},
    {field_opcode, 1},
  [13] =
    {field_instructions, 4},
    {field_locals, 3},
    {field_name, 1},
  [16] =
    {field_params, 1},
    {field_returns, 3},
  [18] =
    {field_label, 0},
    {field_operand, 2},
  [20] =
    {field_instructions, 5},
    {field_locals, 4},
    {field_name, 1},
    {field_stack, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '$') ADVANCE(10);
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '+') ADVANCE(44);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '0') ADVANCE(29);
      if (lookahead == ':') ADVANCE(39);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == '\'' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(36);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_function_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == 'b') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(12);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_char_escape);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'g') ADVANCE(4);
      if (lookahead == 'h') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == 'j') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == 's') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_call);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_heap);
      END_STATE();
    case 39:
      if (lookahead == 'h') ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_inst);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_jump);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_label);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_height);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 16},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 0},
  [114] = {(TSStateId)(-1)},
  [115] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_function_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_char_escape] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_inst] = ACTIONS(1),
    [anon_sym_height] = ACTIONS(1),
    [anon_sym_label] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_heap] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(108),
    [sym_comment] = STATE(1),
    [sym_data_label] = STATE(39),
    [sym_definition] = STATE(67),
    [sym_func] = STATE(82),
    [sym_custom_instruction] = STATE(82),
    [aux_sym_source_file_repeat1] = STATE(43),
    [aux_sym_source_file_repeat2] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_func] = ACTIONS(11),
    [anon_sym_inst] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(18), 1,
      anon_sym_COLON,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_height,
    ACTIONS(26), 1,
      anon_sym_label,
    ACTIONS(29), 1,
      anon_sym_const,
    ACTIONS(32), 1,
      anon_sym_heap,
    ACTIONS(35), 1,
      anon_sym_call,
    ACTIONS(38), 1,
      anon_sym_get,
    ACTIONS(41), 1,
      anon_sym_set,
    ACTIONS(44), 1,
      anon_sym_out,
    ACTIONS(47), 1,
      anon_sym_in,
    ACTIONS(50), 1,
      anon_sym_jump,
    ACTIONS(53), 1,
      anon_sym_branch,
    STATE(14), 1,
      sym__instruction,
    STATE(42), 1,
      sym_inst_label,
    STATE(2), 2,
      sym_comment,
      aux_sym_instruction_list_repeat1,
    STATE(21), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [73] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_COLON,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(62), 1,
      anon_sym_height,
    ACTIONS(64), 1,
      anon_sym_label,
    ACTIONS(66), 1,
      anon_sym_const,
    ACTIONS(68), 1,
      anon_sym_heap,
    ACTIONS(70), 1,
      anon_sym_call,
    ACTIONS(72), 1,
      anon_sym_get,
    ACTIONS(74), 1,
      anon_sym_set,
    ACTIONS(76), 1,
      anon_sym_out,
    ACTIONS(78), 1,
      anon_sym_in,
    ACTIONS(80), 1,
      anon_sym_jump,
    ACTIONS(82), 1,
      anon_sym_branch,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_instruction_list_repeat1,
    STATE(14), 1,
      sym__instruction,
    STATE(42), 1,
      sym_inst_label,
    STATE(21), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [148] = 21,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(58), 1,
      anon_sym_COLON,
    ACTIONS(62), 1,
      anon_sym_height,
    ACTIONS(64), 1,
      anon_sym_label,
    ACTIONS(66), 1,
      anon_sym_const,
    ACTIONS(68), 1,
      anon_sym_heap,
    ACTIONS(70), 1,
      anon_sym_call,
    ACTIONS(72), 1,
      anon_sym_get,
    ACTIONS(74), 1,
      anon_sym_set,
    ACTIONS(76), 1,
      anon_sym_out,
    ACTIONS(78), 1,
      anon_sym_in,
    ACTIONS(80), 1,
      anon_sym_jump,
    ACTIONS(82), 1,
      anon_sym_branch,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_instruction_list_repeat1,
    STATE(4), 1,
      sym_comment,
    STATE(14), 1,
      sym__instruction,
    STATE(42), 1,
      sym_inst_label,
    STATE(21), 12,
      sym_height,
      sym_label,
      sym_const,
      sym_heap,
      sym_call,
      sym_get,
      sym_set,
      sym_out,
      sym_in,
      sym_jump,
      sym_branch,
      sym_instruction,
  [223] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(5), 1,
      sym_comment,
    ACTIONS(86), 13,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PLUS,
    ACTIONS(88), 15,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_func,
      anon_sym_inst,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [265] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(6), 1,
      sym_comment,
    ACTIONS(90), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(92), 15,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_func,
      anon_sym_inst,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [304] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(7), 1,
      sym_comment,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(96), 15,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_func,
      anon_sym_inst,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [343] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(8), 1,
      sym_comment,
    ACTIONS(98), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
    ACTIONS(100), 15,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_func,
      anon_sym_inst,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [382] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 1,
      sym_comment,
    ACTIONS(104), 8,
      anon_sym_LBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(102), 13,
      sym_identifier,
      aux_sym_number_token3,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [417] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(10), 1,
      sym_comment,
    ACTIONS(108), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(106), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [445] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(11), 1,
      sym_comment,
    ACTIONS(112), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(110), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [473] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(114), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [501] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(118), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [529] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(122), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [557] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(126), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [585] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(130), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [613] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(134), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [641] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(138), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [669] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(142), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [697] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(146), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [725] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(150), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [753] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(154), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [781] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(158), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [809] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(162), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [837] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(166), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [865] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(170), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [893] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(174), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [921] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(178), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [949] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(182), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [977] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(186), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1005] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(190), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1033] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(194), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1061] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(198), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1089] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(204), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(202), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1117] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(206), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1145] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(212), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(210), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1173] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_COLON,
      anon_sym_RBRACE,
    ACTIONS(214), 12,
      sym_identifier,
      anon_sym_height,
      anon_sym_label,
      anon_sym_const,
      anon_sym_heap,
      anon_sym_call,
      anon_sym_get,
      anon_sym_set,
      anon_sym_out,
      anon_sym_in,
      anon_sym_jump,
      anon_sym_branch,
  [1201] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 1,
      anon_sym_AT,
    STATE(38), 1,
      sym_comment,
    STATE(40), 1,
      aux_sym_array_repeat1,
    STATE(46), 1,
      sym__literal,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1239] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 1,
      anon_sym_AT,
    ACTIONS(228), 1,
      anon_sym_LBRACK,
    STATE(39), 1,
      sym_comment,
    STATE(68), 2,
      sym_array,
      sym__literal,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1275] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    ACTIONS(235), 1,
      aux_sym_number_token3,
    ACTIONS(238), 1,
      anon_sym_SQUOTE,
    ACTIONS(241), 1,
      anon_sym_AT,
    STATE(46), 1,
      sym__literal,
    STATE(40), 2,
      sym_comment,
      aux_sym_array_repeat1,
    ACTIONS(232), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1311] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 1,
      anon_sym_AT,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
    STATE(38), 1,
      aux_sym_array_repeat1,
    STATE(41), 1,
      sym_comment,
    STATE(46), 1,
      sym__literal,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1349] = 15,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(246), 1,
      sym_identifier,
    ACTIONS(248), 1,
      anon_sym_height,
    ACTIONS(250), 1,
      anon_sym_label,
    ACTIONS(252), 1,
      anon_sym_const,
    ACTIONS(254), 1,
      anon_sym_heap,
    ACTIONS(256), 1,
      anon_sym_call,
    ACTIONS(258), 1,
      anon_sym_get,
    ACTIONS(260), 1,
      anon_sym_set,
    ACTIONS(262), 1,
      anon_sym_out,
    ACTIONS(264), 1,
      anon_sym_in,
    ACTIONS(266), 1,
      anon_sym_jump,
    ACTIONS(268), 1,
      anon_sym_branch,
    STATE(42), 1,
      sym_comment,
  [1395] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_inst,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_data_label,
    STATE(43), 1,
      sym_comment,
    STATE(47), 1,
      aux_sym_source_file_repeat1,
    STATE(50), 1,
      aux_sym_source_file_repeat2,
    STATE(67), 1,
      sym_definition,
    STATE(82), 2,
      sym_func,
      sym_custom_instruction,
  [1433] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 1,
      anon_sym_AT,
    STATE(37), 1,
      sym__literal,
    STATE(44), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1465] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 1,
      anon_sym_AT,
    STATE(16), 1,
      sym__literal,
    STATE(45), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
    STATE(8), 3,
      sym_number,
      sym_char_literal,
      sym_macro,
  [1497] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(274), 1,
      aux_sym_number_token3,
    STATE(46), 1,
      sym_comment,
    ACTIONS(272), 6,
      anon_sym_RBRACK,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
      anon_sym_SQUOTE,
      anon_sym_AT,
  [1518] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(278), 1,
      anon_sym_DOT,
    STATE(39), 1,
      sym_data_label,
    STATE(67), 1,
      sym_definition,
    STATE(47), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    ACTIONS(276), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [1543] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_inst,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      sym_comment,
    STATE(49), 1,
      aux_sym_source_file_repeat2,
    STATE(82), 2,
      sym_func,
      sym_custom_instruction,
  [1569] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
    ACTIONS(283), 1,
      anon_sym_func,
    ACTIONS(286), 1,
      anon_sym_inst,
    STATE(49), 2,
      sym_comment,
      aux_sym_source_file_repeat2,
    STATE(82), 2,
      sym_func,
      sym_custom_instruction,
  [1593] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_inst,
    ACTIONS(289), 1,
      ts_builtin_sym_end,
    STATE(49), 1,
      aux_sym_source_file_repeat2,
    STATE(50), 1,
      sym_comment,
    STATE(82), 2,
      sym_func,
      sym_custom_instruction,
  [1619] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(51), 1,
      sym_comment,
    STATE(102), 1,
      sym_number,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1640] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(26), 1,
      sym_number,
    STATE(52), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1661] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(33), 1,
      sym_number,
    STATE(53), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1682] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(34), 1,
      sym_number,
    STATE(54), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1703] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(55), 1,
      sym_comment,
    STATE(89), 1,
      sym_number,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1724] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(56), 1,
      sym_comment,
    STATE(85), 1,
      sym_number,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1745] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(291), 1,
      anon_sym_COLON,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(295), 1,
      anon_sym_PLUS,
    STATE(57), 1,
      sym_comment,
    STATE(80), 1,
      sym_instruction_list,
    STATE(81), 1,
      sym_stack_behaviour,
  [1770] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(291), 1,
      anon_sym_COLON,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(297), 1,
      anon_sym_PLUS,
    STATE(58), 1,
      sym_comment,
    STATE(76), 1,
      sym_instruction_list,
    STATE(77), 1,
      sym_stack_behaviour,
  [1795] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(59), 1,
      sym_comment,
    STATE(98), 1,
      sym_number,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1816] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(10), 1,
      sym_number,
    STATE(60), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1837] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(61), 1,
      sym_comment,
    STATE(96), 1,
      sym_number,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1858] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(24), 1,
      sym_number,
    STATE(62), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1879] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(36), 1,
      sym_number,
    STATE(63), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1900] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(18), 1,
      sym_number,
    STATE(64), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1921] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(65), 1,
      sym_comment,
    STATE(95), 1,
      sym_number,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1942] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(222), 1,
      aux_sym_number_token3,
    STATE(15), 1,
      sym_number,
    STATE(66), 1,
      sym_comment,
    ACTIONS(220), 3,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_number_token4,
  [1963] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(67), 1,
      sym_comment,
    ACTIONS(299), 4,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_func,
      anon_sym_inst,
  [1979] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(68), 1,
      sym_comment,
    ACTIONS(301), 4,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_func,
      anon_sym_inst,
  [1995] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(69), 1,
      sym_comment,
    ACTIONS(303), 4,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_func,
      anon_sym_inst,
  [2011] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(70), 1,
      sym_comment,
    ACTIONS(305), 4,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_func,
      anon_sym_inst,
  [2027] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(71), 1,
      sym_comment,
    ACTIONS(307), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2042] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(72), 1,
      sym_comment,
    ACTIONS(309), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2057] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(73), 1,
      sym_comment,
    ACTIONS(311), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2072] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(74), 1,
      sym_comment,
    ACTIONS(313), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2087] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(75), 1,
      sym_comment,
    ACTIONS(315), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2102] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(76), 1,
      sym_comment,
    ACTIONS(317), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2117] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(319), 1,
      anon_sym_PLUS,
    STATE(74), 1,
      sym_instruction_list,
    STATE(77), 1,
      sym_comment,
  [2136] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(78), 1,
      sym_comment,
    ACTIONS(321), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2151] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(79), 1,
      sym_comment,
    ACTIONS(323), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2166] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(80), 1,
      sym_comment,
    ACTIONS(325), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2181] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(327), 1,
      anon_sym_PLUS,
    STATE(78), 1,
      sym_instruction_list,
    STATE(81), 1,
      sym_comment,
  [2200] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(82), 1,
      sym_comment,
    ACTIONS(329), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2215] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(83), 1,
      sym_comment,
    ACTIONS(331), 3,
      ts_builtin_sym_end,
      anon_sym_func,
      anon_sym_inst,
  [2230] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_DOT,
    STATE(17), 1,
      sym_data_label,
    STATE(84), 1,
      sym_comment,
  [2246] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    STATE(79), 1,
      sym_instruction_list,
    STATE(85), 1,
      sym_comment,
  [2262] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(333), 1,
      anon_sym_PERCENT,
    STATE(31), 1,
      sym_port,
    STATE(86), 1,
      sym_comment,
  [2278] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(58), 1,
      anon_sym_COLON,
    STATE(30), 1,
      sym_inst_label,
    STATE(87), 1,
      sym_comment,
  [2294] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(58), 1,
      anon_sym_COLON,
    STATE(11), 1,
      sym_inst_label,
    STATE(88), 1,
      sym_comment,
  [2310] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    STATE(75), 1,
      sym_instruction_list,
    STATE(89), 1,
      sym_comment,
  [2326] = 4,
    ACTIONS(335), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(337), 1,
      anon_sym_SLASH_STAR,
    STATE(90), 1,
      sym_comment,
    ACTIONS(339), 2,
      sym_char,
      sym_char_escape,
  [2340] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(333), 1,
      anon_sym_PERCENT,
    STATE(28), 1,
      sym_port,
    STATE(91), 1,
      sym_comment,
  [2356] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(333), 1,
      anon_sym_PERCENT,
    STATE(29), 1,
      sym_port,
    STATE(92), 1,
      sym_comment,
  [2372] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(58), 1,
      anon_sym_COLON,
    STATE(27), 1,
      sym_inst_label,
    STATE(93), 1,
      sym_comment,
  [2388] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(58), 1,
      anon_sym_COLON,
    STATE(23), 1,
      sym_inst_label,
    STATE(94), 1,
      sym_comment,
  [2404] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(95), 1,
      sym_comment,
    ACTIONS(341), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [2418] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_instruction_list,
    STATE(96), 1,
      sym_comment,
  [2434] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_DOT,
    STATE(25), 1,
      sym_data_label,
    STATE(97), 1,
      sym_comment,
  [2450] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    STATE(83), 1,
      sym_instruction_list,
    STATE(98), 1,
      sym_comment,
  [2466] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(333), 1,
      anon_sym_PERCENT,
    STATE(32), 1,
      sym_port,
    STATE(99), 1,
      sym_comment,
  [2482] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(343), 1,
      sym_identifier,
    STATE(100), 1,
      sym_comment,
  [2495] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(345), 1,
      sym_identifier,
    STATE(101), 1,
      sym_comment,
  [2508] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(347), 1,
      anon_sym_DASH_GT,
    STATE(102), 1,
      sym_comment,
  [2521] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(349), 1,
      anon_sym_SQUOTE,
    STATE(103), 1,
      sym_comment,
  [2534] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(351), 1,
      sym_function_name,
    STATE(104), 1,
      sym_comment,
  [2547] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(353), 1,
      anon_sym_SLASH,
    STATE(105), 1,
      sym_comment,
  [2560] = 4,
    ACTIONS(335), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(337), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(355), 1,
      aux_sym_comment_token1,
    STATE(106), 1,
      sym_comment,
  [2573] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(357), 1,
      sym_function_name,
    STATE(107), 1,
      sym_comment,
  [2586] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(359), 1,
      ts_builtin_sym_end,
    STATE(108), 1,
      sym_comment,
  [2599] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(361), 1,
      sym_identifier,
    STATE(109), 1,
      sym_comment,
  [2612] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(363), 1,
      sym_function_name,
    STATE(110), 1,
      sym_comment,
  [2625] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(365), 1,
      sym_identifier,
    STATE(111), 1,
      sym_comment,
  [2638] = 4,
    ACTIONS(335), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(337), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(367), 1,
      aux_sym_comment_token2,
    STATE(112), 1,
      sym_comment,
  [2651] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(369), 1,
      sym_identifier,
    STATE(113), 1,
      sym_comment,
  [2664] = 1,
    ACTIONS(371), 1,
      ts_builtin_sym_end,
  [2668] = 1,
    ACTIONS(373), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 73,
  [SMALL_STATE(4)] = 148,
  [SMALL_STATE(5)] = 223,
  [SMALL_STATE(6)] = 265,
  [SMALL_STATE(7)] = 304,
  [SMALL_STATE(8)] = 343,
  [SMALL_STATE(9)] = 382,
  [SMALL_STATE(10)] = 417,
  [SMALL_STATE(11)] = 445,
  [SMALL_STATE(12)] = 473,
  [SMALL_STATE(13)] = 501,
  [SMALL_STATE(14)] = 529,
  [SMALL_STATE(15)] = 557,
  [SMALL_STATE(16)] = 585,
  [SMALL_STATE(17)] = 613,
  [SMALL_STATE(18)] = 641,
  [SMALL_STATE(19)] = 669,
  [SMALL_STATE(20)] = 697,
  [SMALL_STATE(21)] = 725,
  [SMALL_STATE(22)] = 753,
  [SMALL_STATE(23)] = 781,
  [SMALL_STATE(24)] = 809,
  [SMALL_STATE(25)] = 837,
  [SMALL_STATE(26)] = 865,
  [SMALL_STATE(27)] = 893,
  [SMALL_STATE(28)] = 921,
  [SMALL_STATE(29)] = 949,
  [SMALL_STATE(30)] = 977,
  [SMALL_STATE(31)] = 1005,
  [SMALL_STATE(32)] = 1033,
  [SMALL_STATE(33)] = 1061,
  [SMALL_STATE(34)] = 1089,
  [SMALL_STATE(35)] = 1117,
  [SMALL_STATE(36)] = 1145,
  [SMALL_STATE(37)] = 1173,
  [SMALL_STATE(38)] = 1201,
  [SMALL_STATE(39)] = 1239,
  [SMALL_STATE(40)] = 1275,
  [SMALL_STATE(41)] = 1311,
  [SMALL_STATE(42)] = 1349,
  [SMALL_STATE(43)] = 1395,
  [SMALL_STATE(44)] = 1433,
  [SMALL_STATE(45)] = 1465,
  [SMALL_STATE(46)] = 1497,
  [SMALL_STATE(47)] = 1518,
  [SMALL_STATE(48)] = 1543,
  [SMALL_STATE(49)] = 1569,
  [SMALL_STATE(50)] = 1593,
  [SMALL_STATE(51)] = 1619,
  [SMALL_STATE(52)] = 1640,
  [SMALL_STATE(53)] = 1661,
  [SMALL_STATE(54)] = 1682,
  [SMALL_STATE(55)] = 1703,
  [SMALL_STATE(56)] = 1724,
  [SMALL_STATE(57)] = 1745,
  [SMALL_STATE(58)] = 1770,
  [SMALL_STATE(59)] = 1795,
  [SMALL_STATE(60)] = 1816,
  [SMALL_STATE(61)] = 1837,
  [SMALL_STATE(62)] = 1858,
  [SMALL_STATE(63)] = 1879,
  [SMALL_STATE(64)] = 1900,
  [SMALL_STATE(65)] = 1921,
  [SMALL_STATE(66)] = 1942,
  [SMALL_STATE(67)] = 1963,
  [SMALL_STATE(68)] = 1979,
  [SMALL_STATE(69)] = 1995,
  [SMALL_STATE(70)] = 2011,
  [SMALL_STATE(71)] = 2027,
  [SMALL_STATE(72)] = 2042,
  [SMALL_STATE(73)] = 2057,
  [SMALL_STATE(74)] = 2072,
  [SMALL_STATE(75)] = 2087,
  [SMALL_STATE(76)] = 2102,
  [SMALL_STATE(77)] = 2117,
  [SMALL_STATE(78)] = 2136,
  [SMALL_STATE(79)] = 2151,
  [SMALL_STATE(80)] = 2166,
  [SMALL_STATE(81)] = 2181,
  [SMALL_STATE(82)] = 2200,
  [SMALL_STATE(83)] = 2215,
  [SMALL_STATE(84)] = 2230,
  [SMALL_STATE(85)] = 2246,
  [SMALL_STATE(86)] = 2262,
  [SMALL_STATE(87)] = 2278,
  [SMALL_STATE(88)] = 2294,
  [SMALL_STATE(89)] = 2310,
  [SMALL_STATE(90)] = 2326,
  [SMALL_STATE(91)] = 2340,
  [SMALL_STATE(92)] = 2356,
  [SMALL_STATE(93)] = 2372,
  [SMALL_STATE(94)] = 2388,
  [SMALL_STATE(95)] = 2404,
  [SMALL_STATE(96)] = 2418,
  [SMALL_STATE(97)] = 2434,
  [SMALL_STATE(98)] = 2450,
  [SMALL_STATE(99)] = 2466,
  [SMALL_STATE(100)] = 2482,
  [SMALL_STATE(101)] = 2495,
  [SMALL_STATE(102)] = 2508,
  [SMALL_STATE(103)] = 2521,
  [SMALL_STATE(104)] = 2534,
  [SMALL_STATE(105)] = 2547,
  [SMALL_STATE(106)] = 2560,
  [SMALL_STATE(107)] = 2573,
  [SMALL_STATE(108)] = 2586,
  [SMALL_STATE(109)] = 2599,
  [SMALL_STATE(110)] = 2612,
  [SMALL_STATE(111)] = 2625,
  [SMALL_STATE(112)] = 2638,
  [SMALL_STATE(113)] = 2651,
  [SMALL_STATE(114)] = 2664,
  [SMALL_STATE(115)] = 2668,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(20),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(101),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(66),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(97),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(44),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(63),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(104),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(54),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(53),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(99),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(86),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(87),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 2), SHIFT_REPEAT(88),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, .production_id = 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, .production_id = 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char_literal, 3, .production_id = 6),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_char_literal, 3, .production_id = 6),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_label, 2, .production_id = 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_label, 2, .production_id = 1),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heap, 3, .production_id = 11),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heap, 3, .production_id = 11),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch, 2, .production_id = 7),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 2, .production_id = 7),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, .production_id = 11),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 11),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inst_label, 2, .production_id = 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inst_label, 2, .production_id = 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_list_repeat1, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_list_repeat1, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_height, 2, .production_id = 7),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_height, 2, .production_id = 7),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const, 3, .production_id = 11),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 3, .production_id = 11),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 3, .production_id = 11),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 3, .production_id = 11),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_height, 3, .production_id = 11),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_height, 3, .production_id = 11),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port, 2, .production_id = 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port, 2, .production_id = 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 1, .production_id = 4),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, .production_id = 4),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__instruction, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__instruction, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 2, .production_id = 8),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, .production_id = 8),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch, 3, .production_id = 11),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch, 3, .production_id = 11),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 3, .production_id = 11),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 3, .production_id = 11),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, .production_id = 7),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, .production_id = 7),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3, .production_id = 11),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, .production_id = 11),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 3, .production_id = 11),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 3, .production_id = 11),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out, 3, .production_id = 11),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out, 3, .production_id = 11),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in, 3, .production_id = 11),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in, 3, .production_id = 11),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 2, .production_id = 7),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2, .production_id = 7),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in, 2, .production_id = 7),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in, 2, .production_id = 7),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out, 2, .production_id = 7),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out, 2, .production_id = 7),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2, .production_id = 7),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, .production_id = 7),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_get, 2, .production_id = 7),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_get, 2, .production_id = 7),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 7),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 7),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heap, 2, .production_id = 7),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heap, 2, .production_id = 7),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const, 2, .production_id = 7),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const, 2, .production_id = 7),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [235] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(90),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(100),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(111),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(110),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2), SHIFT_REPEAT(109),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 2, .production_id = 2),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_list, 3),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction_list, 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_custom_instruction, 6, .production_id = 12),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_custom_instruction, 4, .production_id = 5),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 5, .production_id = 9),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_custom_instruction, 3, .production_id = 3),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4, .production_id = 5),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_custom_instruction, 5, .production_id = 9),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 3, .production_id = 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 6, .production_id = 12),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [337] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stack_behaviour, 4, .production_id = 10),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [353] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [355] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [359] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_URSL(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
